# Basic CI/CD workflow
name: CI

# Controls when the workflow will run
# either push on main
# or opened PR on any branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened ]


jobs:
  # Run unit tests (always)
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get --yes install make
      
      - name: Run unit tests
        run: make test

  
  # Run only when pushed to main
  build_push_integration_tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get --yes install make
      
      - name: Create short commit hash
        run: SHORT_SHA=${GITHUB_SHA::7}
      - name: Build and push
        run: |
          make build git-hash=${{ env.SHORT_SHA }}
          make push

      - name: Integration tests
        run: make integration


