name: unit test PRs

on:
  pull_request:
    types: [ opened ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get --yes install make
      
      - name: Run unit tests
        run: make test

---
name: build, publish and full tests

on:
  push:
    branches: [ "main" ]

jobs:
  build_push_integration_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get --yes install make
      
      - name: Run unit tests
        run: make test

      - name: Build and push
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          make build git-hash=${SHORT_SHA}
          make push

      - name: Integration tests
        run: make integration
