name: Test and build

# Controls when the workflow will run
# either push on main
# or when a PR is opened on any branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened ]


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get --yes install make
  
  # Run unit tests (always)
  unittests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: make test

  
  # Run only when pushed to main
  build_push_integration_tests:
    if: github.event_name == 'push'
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo ${SHORT_SHA}
          make build git-hash=${SHORT_SHA}
          make push

      - name: Integration tests
        run: make integration

